name = "ids"
version = "0.12.0"
licences = ["Apache-2.0"]
description = "✨ Unique IDs for Gleam"
repository = { type = "github", user = "rvcas", repo = "ids" }
gleam = ">= 0.32.2"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_otp = "~> 0.10"
gleam_erlang = "~> 0.25"

[dev-dependencies]
gleeunit = "~> 1.0"
